<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Manjusha" failures="1" tests="4" name="Test" time="22.988" errors="0" timestamp="2021-05-26T15:57:20 IST">
  <testcase classname="Practice.J2_RetryFailedTestCase_Test" name="Test" time="8.595">
    <skipped/>
  </testcase> <!-- Test -->
  <testcase classname="Practice.J2_RetryFailedTestCase_Test" name="Test" time="4.674">
    <skipped/>
  </testcase> <!-- Test -->
  <testcase classname="Practice.J2_RetryFailedTestCase_Test" name="Test" time="5.147">
    <skipped/>
  </testcase> <!-- Test -->
  <testcase classname="Practice.J2_RetryFailedTestCase_Test" name="Test" time="4.501">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Practice.J2_RetryFailedTestCase_Test.Test(J2_RetryFailedTestCase_Test.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test -->
</testsuite> <!-- Test -->
